### ISSUE TITLE
Theme/Coloring

### ISSUE THREAD

**Issue by Wiz1991** [fpellicero/react-bottom-drawer#10]
There is currently no way to change the colors of the drawer.

**Comment by BrianRuizy** [comment]
@Wiz1991 @fpellicero 

I found a **hacky** way of styling the component which I needed for my dark theme.
Wrap the drawer in a class, and modify the class using [child selectors](https://www.bitdegree.org/learn/css-child-selector). 

You can also modify the border-radius this way.

```html
<div className="drawer">
      <Drawer>
          <p>asdf</p>
      </Drawer>
    </div>
```

```css
.drawer div:nth-child(2){
    background: var(--card-bg);
    color: var(--primary-text-color);
    padding-bottom: 2rem;
}
```
![Untitled design](https://user-images.githubusercontent.com/23439187/110374677-8f7e7f80-8016-11eb-9efd-19ee7f41c6a6.png)
